<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="adm_Listar_mod_productos.aspx.cs" Inherits="TIF_Grupo_12.adm_Listar_mod_productos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style2 {
            width: 100%;
        }
        .auto-style4 {
            width: 166px;
        }
        .auto-style5 {
            width: 337px;
        }
        .auto-style9 {
            width: 151px;
        }
        .auto-style10 {
            width: 174px;
        }
        .auto-style11 {
            width: 151px;
            height: 23px;
        }
        .auto-style14 {
            height: 23px;
        }
        .auto-style16 {
            width: 558px;
            height: 23px;
        }
        .auto-style17 {
            width: 558px;
        }
        .auto-style19 {
            width: 524px;
        }
        .auto-style20 {
            width: 599px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <table class="auto-style2">
                <tr>
                    <td class="auto-style4">
                        <asp:Label ID="lbl_nombreusuario" runat="server" Font-Names="Arial" Font-Size="Large" ForeColor="Maroon"></asp:Label>
                    </td>
                    <td class="auto-style4">
                        <asp:Label ID="lbl_Titulo" runat="server" Font-Bold="True" Font-Size="Large" Text="Listar productos"></asp:Label>
                        <br />
                    </td>
                    <td class="auto-style5">&nbsp;</td>
                    <td>
                        <asp:HyperLink ID="hl_CerrarSesión" runat="server" NavigateUrl="~/Ingreso.aspx">Cerrar Sesión</asp:HyperLink>
                    </td>
                </tr>
            </table>
            <table class="auto-style2">
                <tr>
                    <td class="auto-style9">&nbsp;</td>
                    <td class="auto-style10">
                        Bsuqeda por descripción:</td>
                    <td class="auto-style17">
                        <asp:TextBox ID="txt_BusquedaxDesc" runat="server"></asp:TextBox>
                    &nbsp;&nbsp;
                        <asp:Button ID="btn_Filtro" runat="server" Text="Buscar" Width="55px" OnClick="btn_Filtro_Click" />
                    </td>
                    <td class="auto-style17" colspan="2">
                        &nbsp;</td>
                    <td class="auto-style19">
                        &nbsp;</td>
                    <td>
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style9">
                        &nbsp;</td>
                    <td colspan="3">
                        <asp:GridView ID="gv_Listarproductos" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="Legajo_Producto"  ForeColor="#333333" GridLines="None" PageSize="6" OnPageIndexChanging="gv_Listarproductos_PageIndexChanging" OnRowCancelingEdit="gv_Listarproductos_RowCancelingEdit" OnRowEditing="gv_Listarproductos_RowEditing" OnRowDeleting="gv_Listarproductos_RowDeleting" OnRowUpdating="gv_Listarproductos_RowUpdating">
                            <AlternatingRowStyle BackColor="White" />
                            <Columns>
                                <asp:TemplateField HeaderText="Imagen">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_Imagen" runat="server" text='<%# Eval("Imagen") %>' Height="150px" Width="150px" />
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Image ID="img_Imagen" runat="server" ImageUrl='<%# Eval("Imagen") %>' Height="150px" Width="150px" />
                                    </ItemTemplate>
                                    <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                    <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Legajo Producto">
                                    <EditItemTemplate>
                                        <asp:Label ID="lbl_LegajoProd" runat="server" Text='<%# Eval("Legajo_Producto") %>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_LegajoProd" runat="server" Text='<%# Eval("Legajo_Producto") %>'></asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                    <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Nombre">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_Nombre" runat="server" Text='<%# Eval("Nombre") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_Nomb" runat="server" Text='<%# Eval("Nombre") %>'></asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Precio">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_Precio" runat="server" Text='<%# Eval("PU") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_Precio" runat="server" Text='<%# Eval("PU") %>'></asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                    <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                </asp:TemplateField>                                
                                <asp:TemplateField HeaderText="Marca">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_Marca" runat="server" Text='<%# Eval("Marca") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_Marca" runat="server" Text='<%# Eval("Marca") %>'></asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                    <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Categoria">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_Categoria" runat="server" Text='<%# Eval("Categoria") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_Categoria" runat="server" Text='<%# Eval("Categoria") %>'></asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                    <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Stock">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_Stock" runat="server" Text='<%# Eval("Stock") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_Stock" runat="server" Text='<%# Eval("Stock") %>'></asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                    <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Descripción">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_Descripcion" runat="server" Text='<%# Eval("Descripción") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_Descripcion" runat="server" Text='<%# Eval("Descripción") %>'></asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                    <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Estado">
                                    <EditItemTemplate>
                                        <asp:CheckBox ID="cb_Estado" runat="server" Checked='<%# Eval("Estado") %>' />
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:CheckBox ID="cb_Estado" runat="server" Checked='<%# Eval("Estado") %>' Enabled="False" Text='<%# Eval("Estado") %>' />
                                    </ItemTemplate>
                                    <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                    <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                </asp:TemplateField>
                            </Columns>
                            <EditRowStyle BackColor="#bdcfeb" />
                            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#EFF3FB" />
                            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#F5F7FB" />
                            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                            <SortedDescendingCellStyle BackColor="#E9EBEF" />
                            <SortedDescendingHeaderStyle BackColor="#4870BE" />
                        </asp:GridView>
                    </td>
                    <td class="auto-style20">
                        <asp:Label ID="lbl_Eliminar" runat="server" Font-Size="X-Large" Text="Seguro que desea eliminar ?" Visible="False"></asp:Label>
                        <br />
                        <asp:Button ID="btn_Eliminar_SI" runat="server" Text="SI" Visible="False" Height="40px" OnClick="btn_Eliminar_SI_Click" Width="40px" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:Button ID="btn_Eliminar_NO" runat="server" Text="NO" Visible="False" Height="40px" OnClick="btn_Eliminar_NO_Click" Width="40px" />
                    </td>
                    <td class="auto-style19">
                        &nbsp;</td>
                    <td>
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style11">
                        &nbsp;</td>
                    <td class="auto-style14" colspan="3">
                        <asp:Label ID="lbl_Mensaje" runat="server" Font-Size="X-Large"></asp:Label>
                    </td>
                    <td class="auto-style16" colspan="2">
                        <asp:HyperLink ID="hl_Indice" runat="server" NavigateUrl="~/Indice_Administrador.aspx">Ir al indice</asp:HyperLink>
                    </td>
                    <td class="auto-style14">
                        &nbsp;</td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>
